#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 ifeq ($(shell uname -s),Darwin)
  include GNUmakefile.macos
 else
  $(error You need to set GNUSTEP_MAKEFILES before compiling!)
 endif
else

include $(GNUSTEP_MAKEFILES)/common.make

#
# Aggregate
#
VERSION = 0.1.0
PACKAGE_NAME = GSPS

# Generator bundles
SUBPROJECTS = \
	GSPS \
	Applications \
#	Documentation

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
-include GNUmakefile.postamble
endif
